from django.urls import path
from . import views 

urlpatterns = [
    path('', views.index, name= "books.index"),
    path('list_books/', views.list_books, name= "books.list_books"),
    path('<int:bookId>/', views.viewbook, name="books.view_one_book"),
    path('aboutus/', views.aboutus, name="books.aboutus"),
    path('html5/links', views.links_view, name='links'),
    path('html5/text/formatting', views.formatting_view, name='formatting'),
    path('html5/listing', views.listing_view, name='listing'),
    path('html5/tables', views.tables_view, name='tables'),
    path('search', views.search_view, name='books.search'),
    path('simple/query', views.simple_query),
    path('complex/query', views.complex_query),
    path('lab8/task1', views.task1_view, name='task1'),
    path('lab8/task2', views.task2_view, name='task2'),
    path('lab8/task3', views.task3_view, name='task3'),
    path('lab8/task4', views.task4_view, name='task4'),
    path('lab8/task5', views.task5_view, name='task5'),
    #path('lab8/task7', views.task7_view, name='task7'),
    path('lab9/task1', views.Lab9task1, name='lab9_task1'),
    path('lab9/task2', views.Lab9task2, name='lab9_task2'),
    path('lab9/task3', views.Lab9task3, name='lab9_task3'),
    path('lab9/task4', views.Lab9task4, name='lab9_task4'),
    path('lab9/task5', views.Lab9task5, name='lab9_task5'),
    path('lab9/task6', views.Lab9task6, name='lab9_task6'),
    path('lab9_part1/listbooks', views.listbooks_part1, name='listbooks_part1'),
    path('lab9_part1/addbook', views.addbook_part1, name='addbook_part1'),
    path('lab9_part1/editbook/<int:id>', views.editbook_part1, name='editbook_part1'),
    path('lab9_part1/deletebook/<int:id>', views.deletebook_part1, name='deletebook_part1'),
    path('lab9_part2/listbooks', views.listbooks_part2, name='listbooks_part2'),
    path('lab9_part2/addbook', views.addbook_part2, name='addbook_part2'),
    path('lab9_part2/editbook/<int:id>', views.editbook_part2, name='editbook_part2'),
    path('lab9_part2/deletebook/<int:id>', views.deletebook_part2, name='deletebook_part2'),
   path('students/', views.student_list, name='student_list'),
    path('students/add/', views.add_student, name='add_student'),
    path('students/update/<int:pk>/', views.update_student, name='update_student'),
    path('students/delete/<int:pk>/', views.delete_student, name='delete_student'),
    path('students2/', views.student2_list, name='student2_list'),
    path('students2/add/', views.add_student2, name='add_student2'),
    path('students2/update/<int:pk>/', views.update_student2, name='update_student2'),
    path('students2/delete/<int:pk>/', views.delete_student2, name='delete_student2'),
    path('members/', views.member_list, name='member_list'),
    path('members/add/', views.add_member, name='add_member'),
    
]
