# Generated by Django 6.0.2 on 2026-05-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0003_author_publisher_remove_student_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='authors',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='book',
            name='pubdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
